services:
  frontend:
    build: ./production
    container_name: ideosphere_frontend
    restart: unless-stopped
    # ❌ PAS DE PORTS ICI. Le proxy s'en charge.
    networks:
      - web-services # Réseau externe pour le proxy Nginx

networks:
  web-services:   # Réseau externe partagé
    external: true

